<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>netstandard2.1</TargetFramework>
        <Nullable>enable</Nullable>
        <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
        <RootNamespace>MonoMod.RuntimeDetour</RootNamespace>
    </PropertyGroup>

    <PropertyGroup>
        <OutputPath>$(SPZ2_PERSISTENT)\mods\MonoMod.RuntimeDetour</OutputPath>
        <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
        <CopyBuildOutputToOutputDirectory>false</CopyBuildOutputToOutputDirectory>
    </PropertyGroup>

    <Target Name="SteamPublish">
        <Exec Command="echo Executing Steam Publishing Bash Commands"/>
        <Exec Command='sh .\Steam\SteamPublish.sh "$(OutputPath)'/>
        <Exec Command="echo Done!"/>
    </Target>

    <ItemGroup>
        <None Update="**/*.dll">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
        <None Update="manifest.json">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="MonoMod.RuntimeDetour" Version="25.3.4"/>
    </ItemGroup>
</Project>
